# https://ubuntu.com/server/docs/service-nfs

- name: Export directory
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: '^{{ mountpoint }}'
    line: "{{ mountpoint }}     *(rw,sync,no_subtree_check)"
    create: true
  notify: Apply export changes
  become: true
