# https://ubuntu.com/server/docs/service-nfs

- name: Bind mount origin for cleaner export path
  become: true
  ansible.posix.mount:
    path: "{{ export }}"
    src: "{{ origin }}"
    opts: bind
    state: mounted
    fstype: none
  when: origin != export

- name: Export directory
  ansible.builtin.blockinfile:
    path: /etc/exports
    marker: "# export number {{ number }} {mark}"
    block: |
      {{ export }}     *(rw,sync,no_subtree_check)
    create: true
  notify:
  - Apply export changes
  - Restart NFS server debian
  become: true
