# https://ubuntu.com/server/docs/service-nfs

- name: Symlink origin for cleaner export paths  # https://access.redhat.com/solutions/8098
  ansible.builtin.file:
    src: "{{ origin }}"
    dest: "{{ export }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
  when: origin != export
  become: true

- name: Export directory
  ansible.builtin.blockinfile:
    path: /etc/exports
    marker: "# export number {{ number }} {mark}"
    block: |
      {{ export }}     *(rw,sync,no_subtree_check)
    create: true
  notify: Apply export changes
  become: true
